name: Deploy backend-node to EC2

on:
  push:
    branches: [main]
    paths:
      - 'backend-node/**'
      - '.github/workflows/deploy-backend.yml'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set -e

            cd /home/ec2-user/CRM

            echo "Updating repository..."
            git fetch origin
            git checkout main
            git reset --hard origin/main

            echo "Using Node:"
            /root/.nvm/versions/node/v22.23.2/bin/node -v

            echo "Installing dependencies..."
            cd backend-node
            /root/.nvm/versions/node/v22.23.2/bin/npm install --omit=dev

            echo "Restarting PM2..."
            sudo -n /root/.nvm/versions/node/v22.23.2/bin/pm2 restart crm-backend-node

            echo "Saving PM2..."
            sudo -n /root/.nvm/versions/node/v22.23.2/bin/pm2 save

            echo "Deployment completed successfully."
